name: source_parser
description: A parser use to do everything you want to.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  go_router: ^3.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.10
  universal_html: ^2.0.8
  modal_bottom_sheet: ^2.0.1
  cached_network_image: ^3.2.1
  freezed_annotation: ^2.1.0
  floor: ^1.3.0
  flutter_riverpod: ^1.0.4
  creator: ^0.1.7
  logger: ^1.1.0
  flutter_colorpicker: ^1.0.3
  xpath_selector: ^3.0.1
  json_path: ^0.4.1
  sqlite_viewer: ^1.0.5
  change_case: ^1.0.2
  xpath_selector_html_parser: ^3.0.0
  gbk_codec: ^0.4.0
  uuid: ^3.0.6
  share_plus: ^4.0.10
  file_picker: ^5.0.1
  book_reader: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  floor_generator: ^1.3.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/default_cover.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
