name: source_parser
description: A parser use to do everything you want to.

publish_to: none

version: 1.0.3+265

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^5.0.3
  cached_network_image: ^3.3.1
  charset: ^2.0.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  file_picker: ^8.1.2
  flutter_android_volume_keydown: ^1.0.0
  flutter_colorpicker: ^1.0.3
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.4.9
  go_router: ^14.2.8
  html: ^0.15.0
  http: ^1.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_path: ^0.6.3
  json_view: ^0.4.2
  logger: ^2.0.2+1
  lpinyin: ^2.0.3
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.0.14
  riverpod_annotation: ^2.3.3
  share_plus: ^10.0.2
  url_launcher: ^6.1.14
  xpath_selector: ^3.0.1
  xpath_selector_html_parser: ^3.0.0
  # flutter_tts: ^4.0.2
  blurhash_ffi: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  go_router_builder: ^2.4.1
  isar_generator: ^3.0.5
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - asset/image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/image/icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "asset/image/icon.jpg"
  windows:
    generate: true
    image_path: "asset/image/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "asset/image/launcher_Icon_macos_512.png"

flutter_native_splash:
  color: "#ffffff"
  image: "asset/image/splash.jpg"
  ios_content_mode: scaleAspectFit
  android_12:
    icon_background_color: "#ffffff"
    image: "asset/image/logo.jpg"
