name: source_parser
description: A parser use to do everything you want to.

publish_to: none

version: 1.0.0+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  book_reader: ^0.0.7
  # book_reader:
  #   path: ../book_reader
  cached_network: ^1.0.3
  cached_network_image: ^3.2.3
  creator: ^0.3.2
  creator_watcher: ^0.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  flutter_colorpicker: ^1.0.3
  go_router: ^7.0.0
  html_parser_plus: ^0.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_view: ^0.4.2
  logger: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - asset/image/default_cover.jpg
